server.port: 8080
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka.binder.brokers: kafka-kafka-brokers.kafka:9092
      bindings:
        producer-out-0:
          destination: webfluxDemo
          contentType: application/json